// ============================================
// Datos mock para el Módulo de Tracking
// Solo para desarrollo — reemplazar con Supabase
// ============================================

import type { B2CTrip, B2BTrip, SheetImportRow } from '@/types/tracking'

// --- Listas predefinidas ---

export const MOCK_CARRIERS = [
    'Retira Meli',
    'DPD next day',
    'MELI FLEX MOOVA',
    'Andreani logistica B2C',
    'La sevillanita',
    'Andesmar',
    'Flota Propia',
    'Envio Pack Pi',
    'Andreani Service Canje',
    'OCA B2C',
    'Oro negro B2C',
    'HOP',
    'Webpack Nextday',
    'Andreani Correo Interior',
    'Del valle',
    'MARKETPLACE',
    'Envio Pack NS',
    'Iflow B2C',
    'ANDREANI PICK UP',
    'Andreani logistica interior',
    'Meli flex webpack',
    'Andreani service',
    'ANDREANI PEDIDOS ESPECIALES',
    'ANDREANI MULTIBULTO B2C',
]

export const MOCK_OPERATORS = [
    'Carlos García',
    'Martín López',
    'Pedro Rodríguez',
    'Juan Fernández',
    'Diego Martínez',
    'Lucas Sánchez',
    'Matías Gómez',
    'Nicolás Díaz',
]

export const MOCK_LABELERS = [
    'Ana Torres',
    'María Ruiz',
    'Laura Paz',
    'Sofía Morales',
]

// Usuario simulado actual
export const MOCK_CURRENT_USER = {
    id: 'user-001',
    name: 'Operador',
    role: 'admin' as const,
}

// --- Datos mock B2C ---

export const MOCK_B2C_TRIPS: B2CTrip[] = [
    {
        id: '1',
        warehouse: 'PL2',
        trip_type: 'b2c',
        date: '2026-03-09',
        carrier: 'Andreani',
        trip_number: '100234',
        operators: ['Carlos García', 'Martín López'],
        pallet_count: 12,
        port: 'A3',
        task_count: 45,
        status: 'picking',
        pallets_dispatched: 4,
        labeler: 'Ana Torres',
        documents_printed: false,
        created_by: 'user-001',
        created_at: '2026-03-09T08:00:00Z',
        updated_at: '2026-03-09T10:30:00Z',
    },
    {
        id: '2',
        warehouse: 'PL2',
        trip_type: 'b2c',
        date: '2026-03-09',
        carrier: 'OCA',
        trip_number: '100235',
        operators: ['Pedro Rodríguez'],
        pallet_count: 8,
        port: 'B1',
        task_count: 32,
        status: 'released',
        pallets_dispatched: 8,
        labeler: 'María Ruiz',
        documents_printed: true,
        created_by: 'user-001',
        created_at: '2026-03-09T07:30:00Z',
        updated_at: '2026-03-09T09:00:00Z',
    },
    {
        id: '3',
        warehouse: 'PL2',
        trip_type: 'b2c',
        date: '2026-03-09',
        carrier: 'Cruz del Sur',
        trip_number: '100236',
        operators: ['Juan Fernández', 'Diego Martínez'],
        pallet_count: 15,
        port: '5',
        task_count: 60,
        status: 'pending',
        pallets_dispatched: 0,
        labeler: 'Laura Paz',
        documents_printed: false,
        created_by: 'user-002',
        created_at: '2026-03-07T09:00:00Z',
        updated_at: '2026-03-07T09:00:00Z',
    },
    {
        id: '4',
        warehouse: 'PL2',
        trip_type: 'b2c',
        date: '2026-03-08',
        carrier: 'Via Cargo',
        trip_number: '100230',
        operators: ['Lucas Sánchez'],
        pallet_count: 6,
        port: 'C2',
        task_count: 18,
        status: 'invoiced',
        pallets_dispatched: 6,
        labeler: 'Sofía Morales',
        documents_printed: true,
        created_by: 'user-001',
        created_at: '2026-03-08T07:00:00Z',
        updated_at: '2026-03-08T16:00:00Z',
    },
    {
        id: '5',
        warehouse: 'PL2',
        trip_type: 'b2c',
        date: '2026-03-09',
        carrier: 'Transporte Lara',
        trip_number: '100237',
        operators: ['Matías Gómez', 'Nicolás Díaz'],
        pallet_count: 20,
        port: 'D1',
        task_count: 75,
        status: 'closing_pending_invoice',
        pallets_dispatched: 18,
        labeler: 'Ana Torres',
        documents_printed: true,
        created_by: 'user-001',
        created_at: '2026-03-09T06:30:00Z',
        updated_at: '2026-03-09T11:00:00Z',
    },
    {
        id: '6',
        warehouse: 'PL2',
        trip_type: 'b2c',
        date: '2026-03-07',
        carrier: 'Expreso Quilmes',
        trip_number: '100228',
        operators: ['Carlos García'],
        pallet_count: 4,
        port: '7',
        task_count: 12,
        status: 'cancelled',
        pallets_dispatched: 0,
        labeler: 'María Ruiz',
        documents_printed: false,
        created_by: 'user-002',
        created_at: '2026-03-05T08:00:00Z',
        updated_at: '2026-03-05T10:00:00Z',
    },
]

// --- Datos mock B2B ---

export const MOCK_B2B_TRIPS: B2BTrip[] = [
    {
        id: '10',
        warehouse: 'PL2',
        trip_type: 'b2b',
        date: '2026-03-09',
        carrier: 'Andreani',
        vehicle_plate: 'AB 123 CD',
        trip_number: '200100',
        client: 'Mercado Libre',
        client_shift: '08:00 - 12:00',
        task_count: 30,
        port: 'E2',
        pallets: 10,
        operators: ['Carlos García', 'Pedro Rodríguez'],
        documents_printed: true,
        detail: 'Carga completa electrónica',
        comments: 'Confirmar recepción con depósito destino',
        bulk_cargo: false,
        status: 'picking',
        created_by: 'user-001',
        created_at: '2026-03-09T07:00:00Z',
        updated_at: '2026-03-09T10:00:00Z',
    },
    {
        id: '11',
        warehouse: 'PL2',
        trip_type: 'b2b',
        date: '2026-03-09',
        carrier: 'Via Cargo',
        vehicle_plate: 'EF 456 GH',
        trip_number: '200101',
        client: 'Farmacity',
        client_shift: 'Turno Tarde',
        task_count: 15,
        port: 'F1',
        pallets: 6,
        operators: ['Martín López'],
        documents_printed: false,
        detail: 'Productos farmacéuticos - cadena de frío',
        comments: '',
        bulk_cargo: false,
        status: 'pending',
        created_by: 'user-001',
        created_at: '2026-03-09T08:30:00Z',
        updated_at: '2026-03-09T08:30:00Z',
    },
    {
        id: '12',
        warehouse: 'PL2',
        trip_type: 'b2b',
        date: '2026-03-09',
        carrier: 'Cruz del Sur',
        vehicle_plate: 'IJ 789 KL',
        trip_number: '200102',
        client: 'Coto',
        client_shift: '06:00 - 10:00',
        task_count: 50,
        port: 'G3',
        pallets: 22,
        operators: ['Diego Martínez', 'Lucas Sánchez', 'Matías Gómez'],
        documents_printed: true,
        detail: 'Alimentos secos y bebidas',
        comments: 'Entrega urgente - reposición de góndola',
        bulk_cargo: true,
        status: 'released',
        created_by: 'user-001',
        created_at: '2026-03-09T05:00:00Z',
        updated_at: '2026-03-09T09:30:00Z',
    },
    {
        id: '13',
        warehouse: 'PL2',
        trip_type: 'b2b',
        date: '2026-03-08',
        carrier: 'OCA',
        vehicle_plate: 'MN 012 OP',
        trip_number: '200098',
        client: 'Jumbo',
        client_shift: 'Sin turno asignado',
        task_count: 25,
        port: '12',
        pallets: 14,
        operators: ['Juan Fernández'],
        documents_printed: true,
        detail: 'Artículos de limpieza',
        comments: '',
        bulk_cargo: false,
        status: 'invoiced',
        created_by: 'user-002',
        created_at: '2026-03-08T06:00:00Z',
        updated_at: '2026-03-08T15:00:00Z',
    },
]

// --- Datos simulados de importación desde Sheet ---

export const MOCK_SHEET_IMPORTS: SheetImportRow[] = [
    {
        _sheetRowId: 'sheet-1',
        date: '2026-03-09',
        carrier: 'Andreani',
        vehicle_plate: 'QR 345 ST',
        trip_number: '200105',
        client: 'Garbarino',
        client_shift: '14:00 - 18:00',
        task_count: 20,
        port: 'H1',
        pallets: 8,
        operators: ['Carlos García'],
        documents_printed: false,
        detail: 'Electrodomésticos grandes',
        comments: 'Requiere montacarga especial',
        bulk_cargo: false,
    },
    {
        _sheetRowId: 'sheet-2',
        date: '2026-03-09',
        carrier: 'Via Cargo',
        vehicle_plate: 'UV 678 WX',
        trip_number: '200106',
        client: 'Sodimac',
        client_shift: 'Mañana',
        task_count: 35,
        port: 'I2',
        pallets: 15,
        operators: ['Martín López', 'Diego Martínez'],
        documents_printed: false,
        detail: 'Materiales de construcción',
        comments: '',
        bulk_cargo: true,
    },
    {
        _sheetRowId: 'sheet-3',
        date: '2026-03-10',
        carrier: 'Cruz del Sur',
        vehicle_plate: 'YZ 901 AB',
        trip_number: '200107',
        client: 'Easy',
        client_shift: '10:00 - 14:00',
        task_count: 12,
        port: 'J3',
        pallets: 5,
        operators: ['Pedro Rodríguez'],
        documents_printed: false,
        detail: 'Herramientas y ferretería',
        comments: 'Verificar stock antes de despachar',
        bulk_cargo: false,
    },
]
